## Inheritance

In [2]:
class Father:
    def __init__(self):
        print("Inside Father class")
    def disp(self):
        print("Father instance method")
class Child(Father):
    def __init__(self):
        print("Inside Child class")
    def show(self):
        print("Child instance method")
c = Child()
c.disp()
c.show()

Inside Child class
Father instance method
Child instance method


In [7]:
class Father:
    def __init__(self):
        print("Inside Father class")
        self.a = 5
    def disp(self):
        print("Father instance method")
        print(self.a)
class Child(Father):
    def __init__(self):
        print("Inside Child class")
    def show(self):
        print("Child instance method")
c = Child()
f = Father()
f.disp()
c.show()
f.show()

Inside Child class
Inside Father class
Father instance method
5
Child instance method


AttributeError: 'Father' object has no attribute 'show'

In [10]:
class Father:
    def __init__(self,a):
        print("Inside Father class")
        self.a = a
    def disp(self):
        print("Father instance method")
class Child(Father):
    def show(self):
        print("Child instance method")
        print(self.a)
c = Child(1)
c.show()
c.disp()

Inside Father class
Child instance method
1
Father instance method


In [11]:
class Father:
    def __init__(self):
        print("Inside Father class")
        self.a = 5
    def disp(self):
        print("Father instance method")
        print(self.a)
class Child(Father):
    def __init__(self):
        super().__init__()
        print("Inside Child class")
    def show(self):
        print("Child instance method")
c = Child()
c.disp()
c.show()

Inside Father class
Inside Child class
Father instance method
5
Child instance method


In [14]:
class Father:
    def __init__(self,a):
        print("Inside Father class")
        self.a = a
    def disp(self):
        print("Father instance method")
        print(self.a)
class Child(Father):
    def __init__(self,b,a):
        super().__init__(a)
        self.b = b
        print("Inside Child class")
    def show(self):
        print("Child instance method")
c = Child(2,5)
c.disp()
c.show()

Inside Father class
Inside Child class
Father instance method
5
Child instance method


In [15]:
class Father:
    def __init__(self,a):
        print("Inside Father class")
        self.a = a
    def disp(self):
        print("Father instance method")
        print(self.a)
class Child(Father):
    def __init__(self,b,a):
        Father.__init__(self,a)
        self.b = b
        print("Inside Child class")
    def show(self):
        print("Child instance method")
c = Child(2,5)
c.disp()
c.show()

Inside Father class
Inside Child class
Father instance method
5
Child instance method


## Multilevel Inheritance

In [21]:
class Father:
    def __init__(self):
        print("Inside Father class")
        self.a = 5
    def disp(self):
        print("Father instance method")
        print(self.a)
class Child(Father):
    def __init__(self):
        super().__init__()
        print("Inside Child class")
    def show(self):
        print("Child instance method")
class GrandChild(Child):
    def __init__(self):
        super().__init__()
        print("Inside Grand child class")
    def show(self):
        print("Grand child instance method")
        super().show()
g = GrandChild()
g.show()
g.disp()

Inside Father class
Inside Child class
Inside Grand child class
Grand child instance method
Child instance method
Father instance method
5


## Hierarchical Inheritance

In [20]:
class Father:
    def __init__(self):
        print("Inside Father class")
        self.a = 5
    def disp(self):
        print("Father instance method")
        print(self.a)
class Son(Father):
    def __init__(self):
        print("Inside Son Class")
        super().__init__()
    def show(self):
        print("Son class instance method")
class Daughter(Father):
    def __init__(self):
        print("Inside Daughter Class")
        super().__init__()
    def show(self):
        print("Daughter class instance method")
s = Son()
d = Daughter()
s.show()
d.show()
s.disp()
d.disp()

Inside Son Class
Inside Father class
Inside Daughter Class
Inside Father class
Son class instance method
Daughter class instance method
Father instance method
5
Father instance method
5


## Multiple Inheritance

In [15]:
class Father:
    def __init__(self):
        super().__init__()
        print("Inside Father class")
        self.a = 5
    def disp(self):
        print("Father instance method")
        print(self.a)
class Mother:
    def __init__(self):
        super().__init__()
        print("Inside Mother class")
        self.b = 10
    def display(self):
        print("Mother instance method")
        print(self.b)
class Son(Father,Mother):
    def __init__(self):
        super().__init__()
        print("Inside son class")
    def show(self):
        print("Son class instance method")
s = Son()
s.disp()
s.display()
print(Son.mro())

Inside Mother class
Inside Father class
Inside son class
Father instance method
5
Mother instance method
10
[<class '__main__.Son'>, <class '__main__.Father'>, <class '__main__.Mother'>, <class 'object'>]


In [16]:
class X:
    pass
class Y:
    pass
class Z:
    pass
class A(X,Y):
    pass
class B(Y,Z):
    pass
class M(B,A,Z):
    pass
print(M.mro())

[<class '__main__.M'>, <class '__main__.B'>, <class '__main__.A'>, <class '__main__.X'>, <class '__main__.Y'>, <class '__main__.Z'>, <class 'object'>]


In [18]:
class X:
    pass
class Y:
    pass
class Z:
    pass
class A(X,Y):
    pass
class B(Z):
    pass
class M(B,A):
    pass
print(M.mro())

[<class '__main__.M'>, <class '__main__.B'>, <class '__main__.Z'>, <class '__main__.A'>, <class '__main__.X'>, <class '__main__.Y'>, <class 'object'>]


In [ ]:
class X:
    pass
class Y:
    pass
class Z:
    pass
class A(X,Y):
    pass
class B(Y,Z):
    pass
class M(B,A,Z):
    pass
print(M.mro())

In [ ]:
M = mro(B) + mro(A) + mro(Z) + BAZO
M = BYZO + AXYO + ZO + BAZO
M = MB + YZO + AXYO + ZO + AZO
M = MBA + YZO + XYO + ZO + ZO
M = MBAX + YZO + YO + ZO + ZO
MBAXYZO








In [19]:
class X:
    pass
class Y:
    pass
class Z:
    pass
class A(X,Y):
    pass
class B(Y,X):
    pass
class M(B,A,Z):
    pass
print(M.mro())

TypeError: Cannot create a consistent method resolution
order (MRO) for bases Y, X, object

In [ ]:
M = BYXO + AXYO + ZO + BAZO
M = MB + YXO + AXYO + ZO + AZO
M = MBA +YXO+XYO+ZO+ZO
M = MBA + YXO +XYO + O + O









In [22]:
class A:
    pass
class B:
    pass
class C:
    pass
class P(A):
    pass
class Q(C,B):
    pass
class R(B,A,Q):
    pass
class X(R,Q,P):
    pass
print(X.mro())

TypeError: Cannot create a consistent method resolution
order (MRO) for bases B, A, Q

## Polymorphism

In [30]:
class Area:
    def display(self,a,b=None):
        if b == None:
            print(a*a)
        else:
            print(a*b)
    def __str__(self):
        return f"Object created"
a = Area()
a.display(5)
a.display(4,2)
b = Area()
print(a)

25
8
Object created


In [36]:
class A:
    def __init__(self,a,b):
        self.a = a
        self.b = b
    def __add__(self,other):
        return self.a + other.a + self.b + other.b
    def __mul__(self,other):
        return self.a * other.a
    def __truediv__(self,other):
        return self.a/other.a
    def __sub__(self,other,third):
        return self.a - other.a - third.a
a1 = A(2,3)
a2 = A(4,7)
print(a1+a2)
print(a1*a2)
print(a1/a2)
a3 = A(3,2)
print(a1-a2-a3)
        
        
        
        
        
        
        
        

16
8
0.5


TypeError: __sub__() missing 1 required positional argument: 'third'

In [ ]:
== - __eq__
< - __lt__
> - __gt__
!= - __ne__
<= - __le__
>= - __ge__

In [1]:
class A:
    def __init__(self,a,b):
        self.a = a
        self.b = b
    def __gt__(self,other):
        if self.a > other.a:
            return "First object is greater"
        else:
            return "Second object is greater"
    def __eq__(self,other):
        if self.a == other.a:
            return "Both are equal"
        else:
            return "Not Equal"
a1 = A(3,5)
a2 = A(2,7)
print(a1 > a2)
print(a1 == a2)

First object is greater
Not Equal


## Abstract Class, Abstract Method

In [3]:
from abc import ABC, abstractmethod

class Father(ABC):
    def show(self):
        print("Concrete Method")
    @abstractmethod
    def disp(self):
        pass
class Child(Father):
    def disp(self):
        print("Father abstract method")
c= Child()
c.show()
c.disp()
    
    
    
    
    
    






Concrete Method
Father abstract method


In [4]:
from abc import ABC, abstractmethod
class Car(ABC):
    @abstractmethod
    def mileage(self):
        pass
    @abstractmethod
    def fuel(self):
        pass
class Suzuki(Car):
    def mileage(self):
        print("Mileage is 25kmpl")
    def fuel(self):
        print("fuel type used is petrol")
class Honda(Car):
    def mileage(self):
        print("Mileage is 20kmpl")
    def fuel(self):
        print("fuel type used is CNG")
class Hyundai(Car):
    def mileage(self):
        print("Mileage is 21kmpl")
    def fuel(self):
        print("fuel type used is Diesel")
    def acc(self):
        print("It has all the accessories")
s = Suzuki()
h1 = Honda()
h2 = Hyundai()
s.mileage()
h1.fuel()
h2.acc()
h2.mileage()








Mileage is 25kmpl
fuel type used is CNG
It has all the accessories
Mileage is 21kmpl


In [7]:
from abc import ABC, abstractmethod
import math
class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
class Rectangle(Shape):
    def __init__(self,l,b):
        self.length = l
        self.breadth = b
    def calculate_area(self):
        return self.length * self.breadth
    def __gt__(self,other):
        if self.calculate_area() > other.calculate_area():
            return "First Rectangle has greater area"
        else:
            return "Second Rectangle has greater area"
class Circle(Shape):
    def __init__(self,r):
        self.radius = r
    def calculate_area(self):
        return math.pi*self.radius*self.radius
c = Circle(6)
r1 = Rectangle(3,9)
r2 = Rectangle(4,5)
print(c.calculate_area())
print(r1>r2)
print(Circle.mro())

113.09733552923255
First Rectangle has greater area
[<class '__main__.Circle'>, <class '__main__.Shape'>, <class 'abc.ABC'>, <class 'object'>]


In [9]:
class A: pass
class B: pass
class C: pass
class D:pass
class E:pass
class K1(C,A,B): pass
class K3(A,D): pass
class K2(B,D,E,A): pass
class Z( K1,K3,K2): pass

TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B

In [ ]:
from abc import ABC, abstractmethod
class Employee(ABC):
    def get_empdetails(self):
        self.empid = int(input("Enter employee id: "))
        self.name = input("Enter Name: ")
        self.salary = int(input("Enter basic salary: "))
    def print_empdetails(self):
        print(f"Employee id: {self.empid}")
        print(f"Name: {self.name}")
        print(f"Basic Salary: {self.salary}")
    def get_salary(self):
        return self.salary
    @abstractmethod
    def emp_id(self):
        pass
class Perks(Employee):
    def calculate_perks(self):
        self.da = 0.35*self.salary
        self.hra = 0.17*self.salary
        self.pf = 0.12*self.salary
    def print_perks(self):
        print(f"DA: {self.da}")
        print(f"HRA: {self.hra}")
        print(f"PF: {self.pf}")
        print(f"Total Perks: {self.da+self.hra-self.pf}")
class NetSalary(Perks):
    def netsalary(self):
        self.net_salary = self.salary+self.da+self.hra-self.pf
    def print_netsalary(self):
        self.print_empdetails()
        self.print_perks()
        print(f"Total Salary: {self.net_salary}")
    def emp_id(self):
        return self.empid
e = NetSalary()
e.get_empdetails()
e.calculate_perks()
e.netsalary()
e.print_netsalary()

## Numpy

In [10]:
import numpy as np

In [12]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a.dtype

dtype('int32')

In [15]:
a = np.array([1,'a',3,4])
print(a)

['1' 'a' '3' '4']


In [16]:
a.dtype

dtype('<U11')

In [17]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
a = np.array([1,2,3,4],dtype=float)
print(a)

[1. 2. 3. 4.]


In [3]:
import numpy as np
a = np.array([1,2,3.5,4])
print(a)

[1.  2.  3.5 4. ]


In [4]:
a = np.array([1,0,3,5],dtype=bool)
print(a)

[ True False  True  True]


In [5]:
a = np.array([[1,2,3],[5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [7]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [8]:
a = np.arange(1,8,-1)
print(a)

[]


In [9]:
a = np.arange(8,1,-1)
print(a)

[8 7 6 5 4 3 2]


In [12]:
a = np.arange(1,11)
print(a)
a = a.reshape(2,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
a = np.arange(1,10)
print(a)
a = a.reshape(3,-1)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a = np.arange(1,10)
print(a)
a = a.reshape(-1,3)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a = np.arange(1,5)
print(a)
a = a.reshape(-1,1)
print(a)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [17]:
a = np.arange(1,5)
print(a)
a = a.reshape(1,-1)
print(a)

[1 2 3 4]
[[1 2 3 4]]


In [20]:
a = np.array([[1,2,3],[5,6,7]])
print(a.ndim)
a = a.reshape(-1)
print(a)
print(a.ndim)

2
[1 2 3 5 6 7]
1


In [22]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [24]:
a = np.arange(1,13)
a = a.reshape(3,2,-1)
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [25]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
a = np.zeros((4,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
a = np.random.random((2,4,4))
print(a)

[[[0.76999413 0.33667074 0.40156473 0.53956519]
  [0.19050164 0.35589656 0.66341613 0.52624193]
  [0.94455174 0.91428977 0.47465976 0.60833022]
  [0.01584695 0.10115604 0.47401775 0.23293871]]

 [[0.87895093 0.74522382 0.81996789 0.05877247]
  [0.38045725 0.70845063 0.09435663 0.8654842 ]
  [0.40928532 0.79339523 0.26392761 0.58259944]
  [0.21881359 0.8845967  0.5094361  0.58113888]]]


In [43]:
a = np.random.randint(5,25,size=(3,6))
print(a)

[[ 6 22 22 18 14  8]
 [14  9 14 14  6 18]
 [24 15 20 19  5 17]]


In [86]:
a = np.random.choice(np.arange(1,10))
print(a)

3


In [66]:
a = np.random.choice(np.array((['Rock','Papers','Scissors'])))
print(a)

Papers


In [87]:
a1 = np.arange(10,dtype=np.int8)
a2 = np.arange(12,dtype=np.float64).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [89]:
print(np.size(a1))
print(np.size(a2))
print(np.size(a3))

10
12
8


In [92]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

1
8
4


In [93]:
a2 = a2.astype(np.int16)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
print(a2.dtype)

int16


In [95]:
print(a2.itemsize)

2


## Scalar Operations

In [96]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [97]:
print(a1 + 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [98]:
print(a1 - 2)

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


In [99]:
print(a1*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [101]:
print(a1 == 4)

[[False False False False]
 [ True False False False]
 [False False False False]]


In [102]:
print(a1 >5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


## Vector Operations

In [103]:
print(a1 + a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [105]:
print(a1 * a2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [107]:
print(a1 / a2)

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [108]:
print(a2 - a1)

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [109]:
print(a1 < a2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [111]:
x = np.random.randint(10,30,size=(3,3))
print(x)
print(np.max(x))

[[23 21 27]
 [24 27 10]
 [26 20 24]]
27


In [113]:
print(np.max(x,axis=0))

[26 27 27]


In [114]:
print(np.max(x,axis=1))

[27 27 26]


In [115]:
x = np.random.randint(10,30,size=(3,3,3))
print(x)
print(np.max(x))

[[[27 23 29]
  [19 10 20]
  [13 26 25]]

 [[13 25 15]
  [29 25 19]
  [21 28 17]]

 [[24 20 18]
  [23 16 15]
  [13 13 12]]]
29


In [116]:
print(np.max(x,axis=0))

[[27 25 29]
 [29 25 20]
 [21 28 25]]


In [117]:
print(np.max(x,axis=1))

[[27 26 29]
 [29 28 19]
 [24 20 18]]


In [118]:
print(np.max(x,axis=2))

[[29 20 26]
 [25 29 28]
 [24 23 13]]


In [119]:
x = np.random.randint(10,30,size=(3,3))
print(x)
print(np.sum(x))

[[21 19 15]
 [22 27 11]
 [21 15 13]]
164


In [120]:
print(np.sum(x,axis=0))

[64 61 39]


In [121]:
print(np.sum(x,axis=1))

[55 60 49]


In [124]:
x = np.random.randint(10,30,size=(3,3))
print(x)
print(np.sort(x,axis=0))

[[21 21 29]
 [10 20 28]
 [28 11 20]]
[[10 11 20]
 [21 20 28]
 [28 21 29]]


In [125]:
print(np.sort(x,axis=1))

[[21 21 29]
 [10 20 28]
 [11 20 28]]


In [129]:
a1 = np.arange(6).reshape(3,2)
a2 = np.arange(7,13).reshape(3,2)
print(a1)
print(a2)

x = np.concatenate((a1,a2),axis=0)
print(x)

[[0 1]
 [2 3]
 [4 5]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [130]:
x = np.concatenate((a1,a2),axis=1)
print(x)

[[ 0  1  7  8]
 [ 2  3  9 10]
 [ 4  5 11 12]]


In [140]:
a1 = np.arange(6).reshape(3,2)
a2 = np.arange(7,11).reshape(2,2)
a3 = np.arange(8).reshape(4,2)
print(a1)
print(a2)
print(a3)
x = np.concatenate((a1,a2,a3),axis=0)
print(x)

[[0 1]
 [2 3]
 [4 5]]
[[ 7  8]
 [ 9 10]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [141]:
a = np.array([1,2,3,4,5,6,7,8])
print(np.where(a==4))

(array([3], dtype=int64),)


In [142]:
print(np.where(a>5))

(array([5, 6, 7], dtype=int64),)


In [144]:
a = np.array([[1,2,3],[2,3,2]])
print(np.where(a==2))

(array([0, 1, 1], dtype=int64), array([1, 0, 2], dtype=int64))


In [146]:
a = np.array([[[1,2],[4,1],[2,3]],[[4,1],[1,1],[3,2]]])
print(a)
print(np.where(a==1))

[[[1 2]
  [4 1]
  [2 3]]

 [[4 1]
  [1 1]
  [3 2]]]
(array([0, 0, 1, 1, 1], dtype=int64), array([0, 1, 0, 1, 1], dtype=int64), array([0, 1, 1, 0, 1], dtype=int64))


In [147]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [149]:
print(a[-4])
print(a[::-1])

6
[9 8 7 6 5 4 3 2 1 0]


In [151]:
print(b[2])

[ 8  9 10 11]


In [155]:
print(b[:,2])

[ 2  6 10]


In [154]:
print(b[:,2:3])

[[ 2]
 [ 6]
 [10]]


In [157]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [168]:
print(b[[1]])

[[4 5 6 7]]


In [170]:
print(b[[1],[1,2]])

[5 6]


In [174]:
print(b[[0,1],[1,2]])

[1 6]


In [158]:
print(b[1:2,1:4])

[[5 6 7]]


In [159]:
print(b[0:2][1:3])

[[4 5 6 7]]


In [167]:
print(b[[0,1]])

[[0 1 2 3]
 [4 5 6 7]]


In [175]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

print(a)
print(b)
print(c)


[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [176]:
print(c[1][1:4][0:8])

[[6 7]]


In [2]:
import numpy as np
c = np.arange(8).reshape(2,2,2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
print(c[0:2][1:4][0:8])

[[[4 5]
  [6 7]]]


In [6]:
print(c[0:2,1:4])

[[[2 3]]

 [[6 7]]]


In [7]:
print(c[0:1,:,0:1])

[[[0]
  [2]]]


In [8]:
c = np.arange(27).reshape(3,3,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
print(c[1:3,2,0:2])

[[15 16]
 [24 25]]


In [10]:
print(c[0:1,0:1,0:1])

[[[0]]]


In [12]:
a = np.array([1,2,3,4,5,6,7,8,9])
x = np.array_split(a,3)
print(x)
x = np.array_split(a,4)
print(x)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [13]:
x = np.array_split(a,5)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


In [14]:
x = np.array_split(a,10)
print(x)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([], dtype=int32)]


In [18]:
a = np.arange(12).reshape(3,4)
print(a)
x = np.array_split(a,3,axis=0)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [17]:
x = np.array_split(a,3,axis=1)
x

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [19]:
x = np.array_split(a,5,axis=1)
x

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([], shape=(3, 0), dtype=int32)]

In [20]:
a = np.arange(12).reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [21]:
x = np.array_split(a,3,axis=0)
x

[array([[[0, 1],
         [2, 3]]]),
 array([[[4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11]]])]

In [22]:
x = np.array_split(a,3,axis=1)
x

[array([[[0, 1]],
 
        [[4, 5]],
 
        [[8, 9]]]),
 array([[[ 2,  3]],
 
        [[ 6,  7]],
 
        [[10, 11]]]),
 array([], shape=(3, 0, 2), dtype=int32)]

In [23]:
x = np.array_split(a,3,axis=2)
x

[array([[[ 0],
         [ 2]],
 
        [[ 4],
         [ 6]],
 
        [[ 8],
         [10]]]),
 array([[[ 1],
         [ 3]],
 
        [[ 5],
         [ 7]],
 
        [[ 9],
         [11]]]),
 array([], shape=(3, 2, 0), dtype=int32)]

In [24]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)
print(np.dot(a,b))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [29]:
import numpy as np
class Game:
    def __init__(self):
        print('''Welcome to Number Guessing Game.
Please select the Difficulty Level for the Game''')
        self.start_game()
    def start_game(self):
        self.mode = int(input('''Enter 1 for Easy Mode,
Enter 2 for Hard Mode: '''))
        if self.mode == 1:
            self.num = np.random.randint(1,101)
            self.chances = 6
            self.accept()
        elif self.mode == 2:
            self.num = np.random.randint(1,1001)
            self.chances = 9
            self.accept()
        else:
            print("Enter correct choice")
            self.start_game()
    def accept(self):
        self.user = int(input("Enter your guess: "))
        self.chances -= 1
        self.validate()
    def validate(self):
        if self.user == self.num:
            self.flag = 1
        else:
            self.flag = 0
        self.hint()
    def hint(self):
        if self.chances == 0:
            print(f'''You are out of attempts.
Correct number is {self.num}''')
            return
        if self.flag == 1:
            print("You Guessed Correct")
        else:
            if self.user > self.num:
                print("Enter Lower Number")
                self.accept()
            else:
                print("Enter Higher Number")
                self.accept()
g = Game()        
    

Welcome to Number Guessing Game.
Please select the Difficulty Level for the Game
Enter 1 for Easy Mode,
Enter 2 for Hard Mode: 1
Enter your guess: 40
Enter Lower Number
Enter your guess: 20
Enter Lower Number
Enter your guess: 10
Enter Lower Number
Enter your guess: 5
Enter Lower Number
Enter your guess: 3
You Guessed Correct


In [32]:
import numpy as np
class Matrix:
    def __init__(self,r,c):
        self.rows = r
        self.columns = c
        self.mat = np.zeros((r,c),dtype=int)
    def get_rows(self):
        return self.rows
    def get_columns(self):
        return self.columns
    def set_elements(self):
        for i in range(self.rows):
            for j in range(self.columns):
                self.mat[i][j] = int(input(f"Enter element on {i} row, {j} column"))
    def __add__(self,other):
        if self.mat.shape == other.mat.shape:
            return self.mat + other.mat
        else:
            return "Matrices can't be added"
    def __mul__(self,other):
        if self.columns == other.rows:
            return np.dot(self.mat,other.mat)
        else:
            return "Matrices can't be Multiplied"
m1 = Matrix(2,2)
m1.set_elements()
m2 = Matrix(2,2)
m2.set_elements()
print(m1+m2)
print(m1*m2)

Enter element on 0 row, 0 column1
Enter element on 0 row, 1 column2
Enter element on 1 row, 0 column3
Enter element on 1 row, 1 column4
Enter element on 0 row, 0 column5
Enter element on 0 row, 1 column6
Enter element on 1 row, 0 column7
Enter element on 1 row, 1 column8
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


In [1]:
import numpy as np 
a=np.arange(6).reshape(3,-1)
print(a.shape) 

(3, 2)


In [2]:
class A: 
    def hello(self): 
        print("1",end=",") 
    def hello(self): 
        print("2",end=",") 
class B(A): 
    def __init__(self): 
        self.hello() 
    def hello(self): 
         print("3",end=",") 
         super().hello() 
b=B() 
b.hello() 

3,2,3,2,

In [3]:
class A: 
    money=5000 
    def __init__(self): 
        self.money+=A.money 
class B(A): 
    def display(self): 
        self.money+=2000 
        print(self.money) 
obj=B() 
obj.display()

12000


In [4]:
class A: 
    a=20 
    def __init__(self): 
        self.a+=10 
class B(A): 
    a=15 
    def buy(self): 
        pass 
class C(B,A): 
    a=30 
    def buy(self): 
        print(self.a) 
obj=C() 
obj.buy()

40


In [5]:
class A: 
    money=100000 
    def buy(self): 
        super().buy() 
        self.money=5000 
class B(A): 
    def buy(self): 
        self.money=3000 
class C(A):
    money=30000 
    def buy(self): 
        self.money=10000 
class D(B,C): 
    B.money+=C.money 
    def buy(self): 
        return self.money 
obj=D() 
print(obj.buy()) 

130000


In [6]:
class A: 
    money=100000 
    def buy(self): 
        super().buy() 
        self.money=5000 
class B(A): 
    def buy(self): 
        self.money=3000 
class C(A):
    money=30000 
    def buy(self): 
        self.money=10000 
class D(C,B): 
    B.money+=C.money 
    def buy(self): 
        return self.money 
obj=D() 
print(obj.buy()) 

30000


In [7]:
class A: 
    def __init__(self): 
        super().__init__() 
        print("1",end=",") 
class B(A): 
    def __init__(self): 
        super().__init__() 
        print("2",end=",") 
class C(object): 
    def __init__(self): 
        super().__init__() 
        print("3",end=",") 
class D(C,B): 
    def __init__(self): 
        super().__init__() 
        print("4",end=",") 
obj=D() 

1,2,3,4,

In [8]:
import numpy as np 
a=np.array(5) 
b=np.array([5,7,8]) 
print(b+a)

[10 12 13]


In [36]:
import numpy as np
a = np.array([[[1,2,3],[3,2,1]],[[3,1,4],[4,6,7]]])
x = np.array_split(a,25,axis=1)
x[4] = 3
print(x[4])
x

3


[array([[[1, 2, 3]],
 
        [[3, 1, 4]]]),
 array([[[3, 2, 1]],
 
        [[4, 6, 7]]]),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 3,
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0, 3), dtype=int32),
 array([], shape=(2, 0

In [41]:
a = np.array([[[1,2,3],[3,2,1]],[[3,1,4],[4,6,7]]])
print(np.where(a==3))
print(np.where(a==3)[1].shape)

(array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64), array([2, 0, 0], dtype=int64))
(3,)


In [42]:
class A:
    pass
class B:
    pass
class C(A,B):
    pass
class P(C,A):
    pass
class Q(B,C):
    pass
class R(A):
    pass
class X(Q,P,R):
    pass
print(X.mro())

TypeError: Cannot create a consistent method resolution
order (MRO) for bases B, C

In [43]:
class A:
    pass
class B:
    pass
class C:
    pass
class P(C,A):
    pass
class Q(B,C):
    pass
class R(A):
    pass
class X(Q,P,R):
    pass
print(X.mro())

[<class '__main__.X'>, <class '__main__.Q'>, <class '__main__.B'>, <class '__main__.P'>, <class '__main__.C'>, <class '__main__.R'>, <class '__main__.A'>, <class 'object'>]


In [44]:
class A:
    pass
class B:
    pass
class C(A,B):
    pass
class P(C,A):
    pass
class Q(C,B):
    pass
class R(A):
    pass
class X(Q,P,R):
    pass
print(X.mro())

[<class '__main__.X'>, <class '__main__.Q'>, <class '__main__.P'>, <class '__main__.C'>, <class '__main__.R'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]


In [ ]:
mro = X + [mro(Q)+mro(P)+mro(R)+QPRO]
mro = X + [QCABO + PCABO + RAO + QPRO]

In [57]:
import numpy as np
class BaseSalesData:
    sales = np.array([ 
[[120,10], [140,12], [130,11], [150,13], [135,10]], 
[[80,15],  [90,18],  [85,16],  [88,17],  [92,19]], 
[[200,8],  [210,9],  [205,10], [215,8],  [220,7]], 
[[60,20],  [65,22],  [70,21],  [68,23],  [72,24]], 
[[150,12], [155,13], [148,14], [160,15], [158,12]], 
[[230,6],  [240,7],  [235,6],  [245,8],  [250,7]] 
]) 
    def __init__(self):
        self.sales = BaseSalesData.sales
        self.products = self.sales.shape[0]
        self.regions = self.sales.shape[1]

class SalesStabilityAnalysis(BaseSalesData):
    
    def net_units(self):
        net=[]
        for p in range(self.products):
            row = []
            for r in range(self.regions):
                row.append(self.sales[p][r][0] - self.sales[p][r][1])
            net.append(row)
        return np.array(net)
    def risk_products(self):
        risky=[]
        for p in range(self.products):
            for r in range(self.regions):
                if self.sales[p][r][1]>15:
                    risky.append(p)
                    break
        return risky
    def regional_reliability(self):
        net = self.net_units()
        avg = []
        for r in range(self.regions):
            s = 0
            for p in range(self.products):
                s += net[p][r]
            avg.append(s / self.products)
        return avg
    def most_stable_product(self):
        net = self.net_units()
        min_values=[]
        for p in range(self.products):
            min_val = net[p][0]
            for r in range(1,self.regions):
                if net[p][r]<min_val:
                    min_val = net[p][r]
            min_values.append(min_val)
        return np.argmax(min_values)
    def normalize_returns(self):
        for p in range(self.products):
            for r in range(self.regions):
                if 14<=self.sales[p][r][1]<=16:
                    self.sales[p][r][1] = 14
        return self.net_units()
    def stability_index(self):
        net = self.net_units()
        index = []
        for p in range(self.products):
            total = 0
            for r in range(self.regions):
                total += net[p][r]
            avg = total/self.regions
            index.append((avg/200)*100)
        return index
    def forecast_readiness(self):
        index = self.stability_index()
        status = []
        for v in index:
            if v>=75:
                status.append('High')
            elif v>=60:
                status.append('Moderate')
            elif v>=50:
                status.append('Low')
            else:
                status.append('Unstable')
        return status
    def planning_priority(self):
        index = self.stability_index()
        temp = list(enumerate(index))
        temp.sort(key=lambda x:x[1],reverse=True)
        order = []
        for i in temp:
            order.append(i[0])
        return order
sa = SalesStabilityAnalysis()
print("Net Units:\n", sa.net_units())
print("Risk Products:", sa.risk_products())
print("Regional Reliability:", sa.regional_reliability()) 
print("Most Stable Product ID:", sa.most_stable_product()) 
print("After Return Normaliza on:\n", sa.normalize_returns())
print("Stability Index:", sa.stability_index()) 
print("Forecast Readiness:", sa.forecast_readiness()) 
print("Planning Priority:", sa.planning_priority()) 

Net Units:
 [[110 128 119 137 125]
 [ 65  72  69  71  73]
 [192 201 195 207 213]
 [ 40  43  49  45  48]
 [138 142 134 145 146]
 [224 233 229 237 243]]
Risk Products: [1, 3]
Regional Reliability: [128.16666666666666, 136.5, 132.5, 140.33333333333334, 141.33333333333334]
Most Stable Product ID: 5
After Return Normaliza on:
 [[110 128 119 137 125]
 [ 66  72  71  71  73]
 [192 201 195 207 213]
 [ 40  43  49  45  48]
 [138 142 134 146 146]
 [224 233 229 237 243]]
Stability Index: [61.9, 35.3, 100.8, 22.5, 70.6, 116.6]
Forecast Readiness: ['Moderate', 'Unstable', 'High', 'Unstable', 'Moderate', 'High']
Planning Priority: [5, 2, 4, 0, 1, 3]
